### ISSUE TITLE
Physical installation breaks virtualized installation

### ISSUE THREAD

**Issue by roschaefer** [MasterprojectOpenStack1516/sourcecode#11]
[This shutdowns all libvirt VMs, even those which weren't created by the installation script](https://github.com/MasterprojectOpenStack2015/sourcecode/blob/master/installation/tools/shutdown_all_vms#L12)

**Comment by snrlx** [comment]
Not an actual fix but take the idea from the pull request and apply it in a fitting manner: https://github.com/MasterprojectOpenStack1516/sourcecode/pull/15

**Comment by snrlx** [comment]
Fixed: https://github.com/MasterprojectOpenStack1516/sourcecode/pull/16
